[project]
name = "coopeverything-ddp"
language = "typescript"
framework = "nextjs"
app_router = true
test_runner = "vitest"
base_dir = "apps/frontend"

[paths]
allowed = [
"apps/frontend/app/",
"apps/frontend/pages/",
"apps/frontend/src/",
"apps/frontend/lib/",
"apps/frontend/components/",
"apps/frontend/tests/",
"docs/",
"scripts/",
"specs/",
]
forbidden = [
".github/",
".git/",
"node_modules/",
".env*",
]

[commands] # executed in apps/frontend during CI
lint = "npm run lint"
format_check = "npm run format:check"
typecheck = "npm run typecheck"
test = "npm run test -- --run"
build = "npm run build"

[generator]
require_tests = true
require_typesafe = true
min_coverage = 0
model = "gpt-4o-mini" # replace with your Codex-connected model
max_repo_files_sample = 600
