name: "Agent Task"
description: "Template for Agent lane tasks"
title: "[Agent Task] <short description>"
labels: ["agent-task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Agent Task Issue

        Please fill out the required fields for an Agent lane task.

  - type: input
    id: goal
    attributes:
      label: "Goal"
      description: "Describe the main objective of this Agent lane task."
      placeholder: "e.g., Add support for agent PR checks"
    validations:
      required: true

  - type: input
    id: scope-allowlist
    attributes:
      label: "Scope allowlist"
      description: "List the only allowed scope for this task (use relative paths)."
      value: ".github/ISSUE_TEMPLATE/"
    validations:
      required: true

  - type: textarea
    id: done-when-checks
    attributes:
      label: "Done when / Checks"
      description: |
        Define the criteria for considering this task complete.
        For agent lane tasks, include a proof-line to be printed in the PR description (required):
        'TEMPLATE=AGENT_TASK_OK'
      placeholder: |
        - All files in .github/ISSUE_TEMPLATE/ are updated as required.
        - PR description contains: TEMPLATE=AGENT_TASK_OK
    validations:
      required: true