---
name: Agent task
description: Run a tiny, verified change via the Agent lane (scoped paths + proof-lines).
title: "agent: <short goal>"
labels:
  - agent
  - automation
body:
  - type: markdown
    attributes:
      value: |
        **Instructions**
        - Keep scope tiny. Provide a clear goal and an explicit path allowlist.
        - The PR MUST print these proof-lines in Checks:
          - `PROOF: ACTIONLINT=OK`
          - `PROOF: YAMLLINT=OK`
          - `PROOF: SMOKE=OK`
          - `PROOF: AGENT_PR_CHECKS=OK`
        - Files changed must be a subset of the allowlist.
  - type: input
    id: goal
    attributes:
      label: Goal
      description: One-sentence goal (what to change/build).
      placeholder: Scaffold /proposals page + add nav link
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope allowlist (paths)
      description: Comma-separated globs, e.g. "apps/frontend/*, codex/*"
      placeholder: apps/frontend/*, codex/*
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details / acceptance
      description: What should be considered done? Any extra proof-lines to print?
      placeholder: |
        Done when: PROOF: PROPOSALS_PAGE=OK printed by smoke.
  - type: checkboxes
    id: acks
    attributes:
      label: Acknowledgements
      options:
        - label: I confirm the changed files must be limited to the allowlist.
          required: true
        - label: I understand PR must show the four proof-lines listed above.
          required: true
