name: Admin - bulk delete runs
on:
  workflow_dispatch:
    inputs:
      preview:
        description: "Preview only (no deletions)"
        type: boolean
        required: true
        default: true
      keep_active:
        description: "Keep newest N runs for active workflows"
        type: number
        required: true
        default: 30

permissions:
  actions: write
  contents: read

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq and gh
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh || true
          gh --version || true

      - name: Build deletion plan
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          KEEP_ACTIVE: ${{ inputs.keep_active }}
        run: |
          set -euo pipefail

          ACTIVE='[".github/workflows/deploy.yml",".github/workflows/package-knowledge.yml"]'

          # Get all workflow paths GitHub knows about
          gh api --paginate /repos/$REPO/actions/workflows -q '.workflows[].path' \
            | jq -s '.' > wf_paths.json

          # Get all runs (includes historical paths)
          gh api --paginate /repos/$REPO/actions/runs -q '.workflow_runs[] | {id, created_at, path}' \
            | jq -s '.' > runs.json

          # Plan:
          #  - delete ALL runs for every workflow path not in ACTIVE
          #  - for ACTIVE, keep newest N, delete the rest
          jq --slurpfile all wf_paths.json --argjson active "$ACTIVE" --argjson keep "$KEEP_ACTIVE" '
            def member($x;$arr): any($arr[]; . == $x);
            def sortdesc: sort_by(.created_at) | reverse;

            . as $runs
            | ($all[0] // []) as $all_paths
            | ($all_paths | map(select( ( . as $p | $active | index($p) | not ) ))) as $deprecated_paths

            | {
                deprecated:   [ $runs[] | select( member(.path; $deprecated_paths) ) ],
                active_keep:  ( [ $runs[] | select( member(.path; $active) ) ]
                                | group_by(.path) | map( (sortdesc)[:$keep] ) | add ),
                active_delete:( [ $runs[] | select( member(.path; $active) ) ]
                                | group_by(.path) | map( (sortdesc)[$keep:] ) | add )
              }
            | .active_keep   = (.active_keep   // [])
            | .active_delete = (.active_delete // [])
            | .to_delete = (.deprecated + .active_delete)
            | { summary: {
                  active_keep:     (.active_keep|length),
                  deprecated_total: (.deprecated|length),
                  active_delete:    (.active_delete|length),
                  total_delete:     (.to_delete|length)
                },
                delete_ids: (.to_delete | map(.id))
              }' runs.json > plan.json

          echo "PLAN SUMMARY:"; jq '.summary' plan.json

      - name: Dry run output
        if: ${{ inputs.preview }}
        run: jq -r '.delete_ids[:30][]' plan.json

      - name: Delete runs
        if: ${{ !inputs.preview }}
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          del_ok=0; del_err=0
          for id in $(jq -r '.delete_ids[]' plan.json); do
            if gh api --method DELETE /repos/$REPO/actions/runs/$id >/dev/null 2>&1; then
              del_ok=$((del_ok+1))
            else
              del_err=$((del_err+1))
            fi
          done
          echo "DELETED=$del_ok ERRORS=$del_err"
