---
name: Agent PR Checks

# yamllint disable-next-line rule:truthy
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    steps:
      - name: Print SMOKE proof
        shell: bash
        run: |
          set -euo pipefail
          echo "PROOF: SMOKE=OK"

  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          yaml_files: |
            .github/workflows/**/*.yml
            .github/workflows/**/*.yaml
          config_file: .yamllint.yaml
      - name: Print YAMLLINT proof
        shell: bash
        run: |
          set -euo pipefail
          echo "PROOF: YAMLLINT=OK"

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-check
          actionlint_flags: >
            --color never
            -shellcheck=never
      - name: Print ACTIONLINT proof
        shell: bash
        run: |
          set -euo pipefail
          echo "PROOF: ACTIONLINT=OK"

  agent_pr_checks:
    name: Agent PR Checks
    runs-on: ubuntu-latest
    needs:
      - smoke
      - yamllint
      - actionlint
    steps:
      - name: Final proof
        shell: bash
        run: |
          set -euo pipefail
          echo "PROOF: AGENT_PR_CHECKS=OK"
