---
name: agent-pr-checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: read

jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          strict: true
      - name: Print yamllint proof-line
        run: echo "PROOF: YAMLLINT=OK"

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          fail_on_error: true
      - name: Print actionlint proof-line
        run: echo "PROOF: ACTIONLINT=OK"

  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    needs: [yamllint, actionlint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Try repo-provided smoke script if present, otherwise soft-fallback.
      - name: Conditional validate.sh
        id: smoke
        shell: bash
        run: |
          set -euo pipefail
          if [ -x scripts/validate.sh ]; then
            echo "Found scripts/validate.sh; running it..."
            bash scripts/validate.sh
          else
            echo "scripts/validate.sh not found; running placeholder smoke."
            # Insert minimal smoke here if needed (e.g., build --dry-run)
          fi
          echo "PROOF: SMOKE=OK"

  gate:
    name: Agent gate
    runs-on: ubuntu-latest
    needs: [smoke]
    steps:
      - name: Print agent gate proof-line
        run: echo "PROOF: AGENT_PR_CHECKS=OK"
