---
name: Agent PR Checks

# yamllint disable-next-line rule:truthy
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    steps:
      - name: Print SMOKE proof
        shell: bash
        run: |
          set -euo pipefail
          echo "PROOF: SMOKE=OK"

  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          yaml_files: |
            .github/workflows/**/*.yml
            .github/workflows/**/*.yaml
          config_data: |
            extends: default
            rules:
              line-length:
                max: 80
                allow-non-breakable-words: true
                allow-non-breakable-inline-mappings: true
              truthy: enable
              document-start: disable
          strict: true
      - name: Print YAMLLINT proof
        shell: bash
        run: |
          set -euo pipefail
          echo "PROOF: YAMLLINT=OK"

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-check
          actionlint_flags: >
            --color never
