name: CI (sanity)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello
        run: echo "CI is wired up."