name: ci/docs

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Markdown style/lint (no apt, uses a prebuilt action)
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md

      # Link checker (fast, containerized; no apt)
      - name: Link check
        uses: lycheeverse/lychee-action@v1
        with:
          # check all markdown files in repo (README + docs, etc.)
          args: >
            --no-progress --verbose --exclude-mail
            --accept 200,204
            --include **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
