name: codex-autolabel
on:
  issues:
    types: [opened, edited]   # handle both create and immediate edits

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Show event + title (debug)
        run: |
          set -euo pipefail
          echo "EVENT=$(jq -r '.action' "$GITHUB_EVENT_PATH")"
          echo "TITLE=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")"

      - name: Add codex-task label when title starts with 'Codex:'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
          case "$title" in
            Codex:*) gh issue edit ${{ github.event.issue.number }} --add-label codex-task -R "$GITHUB_REPOSITORY" ;;
            *) echo "Title does not start with 'Codex:' — no label added" ;;
          esac
