name: codex-secret-smoke
on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Verify CODEX_PAT can call GitHub API
        shell: bash
        run: |
          set -euo pipefail
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.CODEX_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user)
          echo "HTTP_CODE=$code"
          test "$code" = "200"

      - name: Dispatch Deploy workflow
        shell: bash
        run: |
          set -euo pipefail
          code=$(curl -sS -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.CODEX_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/TheEpicuros/ddp/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}')
          echo "DISPATCH_CODE=$code"
          test "$code" = "204"

      - name: Fetch main SHA
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.CODEX_PAT }}
        run: |
          set -euo pipefail
          sha=$(gh api repos/TheEpicuros/ddp/git/ref/heads/main --jq '.object.sha')
          echo "MAIN_SHA=$sha"
