name: codex-autolabel
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Show issue title
        run: |
          set -euo pipefail
          title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
          echo "TITLE=$title"

      - name: Add codex-task label when title starts with Codex:
        if: startsWith(github.event.issue.title, 'Codex:')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          gh issue edit ${{ github.event.issue.number }} --add-label codex-task -R "$GITHUB_REPOSITORY"
