name: codex-secret-smoke
on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Verify CODEX_PAT can call GitHub API
        run: |
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.CODEX_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user)
          echo "HTTP_CODE=$code"
          if [ "$code" != "200" ]; then
            echo "Token check failed"; exit 1
          fi

