name: codex-secret-smoke
on:
  workflow_dispatch:
    inputs:
      dispatch_deploy:
        description: "Trigger Deploy workflow too?"
        required: false
        default: "false"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Verify CODEX_PAT can call GitHub API
        shell: bash
        run: |
          set -euo pipefail
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.CODEX_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user)
          echo "HTTP_CODE=$code"
          test "$code" = "200"

      - name: Show input
        run: echo "dispatch_deploy=${{ inputs.dispatch_deploy }}"

      - name: Dispatch Deploy workflow (opt-in)
        if: ${{ inputs.dispatch_deploy == 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          code=$(curl -sS -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.CODEX_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/TheEpicuros/ddp/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}')
          echo "DISPATCH_CODE=$code"
          test "$code" = "204"
