name: codex-autolabel
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    if: startsWith(github.event.issue.title, 'Codex:')
    runs-on: ubuntu-latest
    steps:
      - name: Add codex-task label
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          gh issue edit ${{ github.event.issue.number }} --add-label codex-task
