name: Deploy Staging to VPS
on:
pull_request:
types: [labeled]
permissions:
contents: read
jobs:
deploy:
if: github.event.label.name == 'staging-ok'
runs-on: ubuntu-latest
steps:
- name: Checkout merged PR head
uses: actions/checkout@v4
with:
fetch-depth: 0
ref: ${{ github.event.pull_request.head.sha }}
  - name: Setup SSH
    run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
      chmod 600 ~/.ssh/id_ed25519
      ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

  - name: Rsync apps/frontend → VPS
    run: |
      rsync -az --delete --exclude '.next/cache' apps/frontend/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}/

  - name: Remote redeploy
    run: |
      ssh -o StrictHostKeyChecking=yes ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_PATH }} && bash -lc './scripts/redeploy-frontend.sh || (echo redeploy script missing; exit 1)'"
