name: Deploy Staging
on:
  pull_request:
    types: [labeled]
jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'staging-ok')
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo deploy skeleton OK