name: Deploy Staging

on:
pull_request:
types: [labeled, synchronize, reopened]
branches: [main]
workflow_dispatch:

permissions:
contents: read

jobs:
deploy:
if: contains(join(github.event.pull_request.labels.*.name, ','), 'staging-ok')
runs-on: ubuntu-latest
concurrency:
group: deploy-staging-${{ github.event.pull_request.number }}
cancel-in-progress: true
steps:
- name: Checkout PR merge ref
uses: actions/checkout@v4
with:
ref: ${{ github.event.pull_request.head.sha }}
- name: Print deploy intent
run: |
echo "Deploying PR #${{ github.event.pull_request.number }} to staging (label detected: staging-ok)."
