name: Deploy Staging

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'staging-ok')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync repo to VPS
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}/

      - name: Restart containers & verify CSS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<'EOF'
          set -euo pipefail
          cd ${{ secrets.VPS_PATH }}
          if [ -f scripts/redeploy-frontend.sh ]; then \
            bash scripts/redeploy-frontend.sh; \
          else \
            echo "Missing scripts/redeploy-frontend.sh" && exit 1; \
          fi
          EOF