name: smoke

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke:
    name: ci/smoke
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch ping
        run: echo "workflow-dispatch-ready"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install validation tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yamllint gh
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint_Linux_x86_64.tar.gz \
            | sudo tar -xzf - -C /usr/local/bin actionlint
      - name: Run validation
        run: bash scripts/validate.sh
      - name: Smoke marker
        run: echo "SMOKE=OK"
