name: smoke

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke:
    name: ci/smoke
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch ping
        run: echo "workflow-dispatch-ready"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install validation tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yamllint gh curl
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash -o /tmp/actionlint.sh
          sudo bash /tmp/actionlint.sh latest /usr/local/bin
          actionlint --version
          echo "ACTIONLINT=OK"

      # Skips until scripts/validate.sh exists on the branch
      - name: Run validation
        if: ${{ hashFiles('scripts/validate.sh') != '' }}
        run: bash scripts/validate.sh

      - name: Smoke marker
        run: echo "SMOKE=OK"
