name: Test OPENAI_API_KEY
on:
  workflow_dispatch:
jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check OPENAI_API_KEY presence
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ OPENAI_API_KEY is NOT set"
            exit 1
          else
            echo "✅ OPENAI_API_KEY is set (value is hidden)"
          fi
